/**                                           
 * @file    build_info.h                      
 * @brief   Git tag and commit information    
 * @warning DO NOT EDIT!                      
 *          Generated by CreateBuildInfo.bat  
 */                                           
                                              
#ifndef BUILD_INFO_H                          
#define BUILD_INFO_H                          
                                              
#define BUILD_DATE    "2020/11/17"          
                                              
#define BUILD_TIME    "15:33:21"          
                                              
#define BUILD_INFO    "3bf2-dirty"          
                                              
#define BUILD_BRANCH  "master"        
                                              
#endif /* BUILD_INFO_H */                     
                                              
