/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import modelURI from './xsens-mti300.glb'

console.log(modelURI)

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useLoader<any>(GLTFLoader, modelURI)

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Default" userData={{ name: 'Default' }}>
          <group
            name="xsens_mti300_imu"
            position={[0, 2.3, 2.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            userData={{ name: 'xsens_mti300_imu' }}
          >
            <group name="xsens_mti300_imu_1" userData={{ name: 'xsens_mti300_imu' }}>
              <mesh
                name="xsens_mti300_imu_5"
                material={nodes.xsens_mti300_imu_5.material}
                geometry={nodes.xsens_mti300_imu_5.geometry}
                userData={{ name: 'xsens_mti300_imu' }}
              />
            </group>
            <group name="xsens_mti300_imu_2" userData={{ name: 'xsens_mti300_imu' }}>
              <mesh
                name="xsens_mti300_imu_6"
                material={nodes.xsens_mti300_imu_6.material}
                geometry={nodes.xsens_mti300_imu_6.geometry}
                userData={{ name: 'xsens_mti300_imu' }}
              />
            </group>
            <group name="xsens_mti300_imu_3" userData={{ name: 'xsens_mti300_imu' }}>
              <mesh
                name="xsens_mti300_imu_7"
                material={nodes.xsens_mti300_imu_7.material}
                geometry={nodes.xsens_mti300_imu_7.geometry}
                userData={{ name: 'xsens_mti300_imu' }}
              />
            </group>
            <group name="xsens_mti300_imu_4" userData={{ name: 'xsens_mti300_imu' }}>
              <mesh
                name="xsens_mti300_imu_8"
                material={nodes.xsens_mti300_imu_8.material}
                geometry={nodes.xsens_mti300_imu_8.geometry}
                userData={{ name: 'xsens_mti300_imu' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
