enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
  - path: .yarn/plugins/@yarnpkg/plugin-redirect-app-builder.js
    spec: 'https://raw.githubusercontent.com/electricui/yarn-redirect-app-builder/master/bundles/%40yarnpkg/plugin-redirect-app-builder.js'
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
packageExtensions:
  chokidar@*:
    dependencies:
      fsevents: 2.1.3
  debug@*:
    dependencies:
      supports-color: 7.1.0
  react-layout-effect@*:
    dependencies:
      react: '*'
  use-memo-one@*:
    dependencies:
      react: '*'
  '@react-spring/web@*':
    dependencies:
      react-dom: '*'
  '@react-spring@*':
    dependencies:
      react-dom: '*'
  react-dom@*:
    dependencies:
      react: '*'
  'react-three-fiber@*':
    dependencies:
      object-assign: '*'
  '@pmmmwh/react-refresh-webpack-plugin@*':
    dependencies:
      webpack: '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  '@react-spring/core@*':
    dependencies:
      react: '*'
  '@react-spring/animated@*':
    dependencies:
      react: '*'
  '@react-spring/shared@*':
    dependencies:
      react: '*'
  victory-zoom-container@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-area@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-axis@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-bar@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-box-plot@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-brush-container@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-brush-line@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-candlestick@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-chart@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-core@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-cursor-container@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-errorbar@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-group@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-histogram@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-legend@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-line@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-pie@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-polar-axis@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-scatter@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-selection-container@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-shared-events@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-stack@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-tooltip@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-voronoi@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  victory-voronoi-container@*:
    dependencies:
      react: '*'
      '@types/react': '*'
  react-spring@*:
    peerDependencies:
      react: '*'
      '@types/react': '*'
  styled-components@*:
    dependencies:
      react-is: '17.0.1'