enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
  - path: .yarn/plugins/@yarnpkg/plugin-redirect-app-builder.js
    spec: 'https://raw.githubusercontent.com/electricui/yarn-redirect-app-builder/master/bundles/%40yarnpkg/plugin-redirect-app-builder.js'
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
packageExtensions:
  '@electricui/charts@*':
    dependencies:
      core-js: '*'
  '@electricui/components-core@*':
    dependencies:
      core-js: '*'
  '@electricui/core-redux-state@*':
    dependencies:
      core-js: '*'
  '@electricui/pondjs@*':
    dependencies:
      core-js: '*'
  '@electricui/components-desktop-three@*':
    dependencies:
      core-js: '*'
  '@pmmmwh/react-refresh-webpack-plugin@*':
    dependencies:
      webpack: '*'
  '@react-spring/animated@*':
    dependencies:
      react: '*'
  '@react-spring/core@*':
    dependencies:
      react: '*'
  '@react-spring/shared@*':
    dependencies:
      react: '*'
  '@react-spring/three@*':
    dependencies:
      react-three-fiber: '*'
      three: 0.123.0
  '@react-spring/web@*':
    dependencies:
      react-dom: '*'
  '@react-spring@*':
    dependencies:
      react-dom: '*'
  '@react-three/drei@*':
    peerDependencies:
      three: '*'
    dependencies:
      'use-asset': '*'
  'troika-three-utils@*':
    peerDependencies:
      'three': '*'
  'troika-three-text@*':
    peerDependencies:
      'three': '*'
  chokidar@*:
    dependencies:
      fsevents: 2.1.3
  debug@*:
    dependencies:
      supports-color: 7.1.0
  drei@*:
    peerDependencies:
      three: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  r3f-troika@*:
    peerDependencies:
      three: '*'
  react-dom@*:
    dependencies:
      react: '*'
  react-layout-effect@*:
    dependencies:
      react: '*'
  react-spring@*:
    peerDependencies:
      '@types/react': '*'
      react: '*'
  react-three-fiber@*:
    dependencies:
      object-assign: '*'
  react-three-fibre@*:
    dependencies:
      three: 0.123.0
  storycap@*:
    dependencies:
      '@storybook/addons': '*'
  styled-components@*:
    dependencies:
      react-is: 17.0.1
  use-memo-one@*:
    dependencies:
      react: '*'
  victory-area@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-axis@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-bar@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-box-plot@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-brush-container@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-brush-line@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-candlestick@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-chart@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-core@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-cursor-container@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-errorbar@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-group@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-histogram@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-legend@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-line@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-pie@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-polar-axis@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-scatter@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-selection-container@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-shared-events@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-stack@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-tooltip@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-voronoi-container@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-voronoi@*:
    dependencies:
      '@types/react': '*'
      react: '*'
  victory-zoom-container@*:
    dependencies:
      '@types/react': '*'
      react: '*'
